// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(TeacherDbContext))]
    [Migration("20260206131713_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionTestWrittenId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("QuestionTestWrittenId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("backend.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerAiId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerTeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerAiId");

                    b.HasIndex("AnswerTeacherId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("backend.models.Correction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TestWrittenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("TestWrittenId");

                    b.ToTable("Corrections");
                });

            modelBuilder.Entity("backend.models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionBankId")
                        .HasColumnType("integer");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("QuestionBankId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("backend.models.QuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("QuestionBanks");
                });

            modelBuilder.Entity("backend.models.QuestionCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionCriterias");
                });

            modelBuilder.Entity("backend.models.QuestionTestWritten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Lines")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("TestWrittenId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestWrittenId");

                    b.ToTable("QuestionTestWrittens");
                });

            modelBuilder.Entity("backend.models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("backend.models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("backend.models.TeacherClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherClasses");
                });

            modelBuilder.Entity("backend.models.TestWritten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RegexQuestionIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherClassId");

                    b.ToTable("TestWrittens");
                });

            modelBuilder.Entity("backend.models.Answer", b =>
                {
                    b.HasOne("backend.models.Correction", "Correction")
                        .WithMany("Answers")
                        .HasForeignKey("CorrectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.QuestionTestWritten", "QuestionTestWritten")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionTestWrittenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correction");

                    b.Navigation("QuestionTestWritten");
                });

            modelBuilder.Entity("backend.models.Comment", b =>
                {
                    b.HasOne("backend.models.Answer", "AnswerAi")
                        .WithMany("AiComments")
                        .HasForeignKey("AnswerAiId");

                    b.HasOne("backend.models.Answer", "AnswerTeacher")
                        .WithMany("TeacherComments")
                        .HasForeignKey("AnswerTeacherId");

                    b.Navigation("AnswerAi");

                    b.Navigation("AnswerTeacher");
                });

            modelBuilder.Entity("backend.models.Correction", b =>
                {
                    b.HasOne("backend.models.Student", "Student")
                        .WithMany("Corrections")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.TestWritten", "TestWritten")
                        .WithMany("Corrections")
                        .HasForeignKey("TestWrittenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TestWritten");
                });

            modelBuilder.Entity("backend.models.Question", b =>
                {
                    b.HasOne("backend.models.QuestionBank", "QuestionBank")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("backend.models.QuestionBank", b =>
                {
                    b.HasOne("backend.models.Teacher", "Teacher")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("backend.models.QuestionCriteria", b =>
                {
                    b.HasOne("backend.models.Question", "Question")
                        .WithMany("QuestionCriterias")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.models.QuestionTestWritten", b =>
                {
                    b.HasOne("backend.models.Question", "Question")
                        .WithMany("QuestionTestWrittens")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.TestWritten", "TestWritten")
                        .WithMany("QuestionTestWrittens")
                        .HasForeignKey("TestWrittenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("TestWritten");
                });

            modelBuilder.Entity("backend.models.Student", b =>
                {
                    b.HasOne("backend.models.TeacherClass", "TeacherClass")
                        .WithMany("Students")
                        .HasForeignKey("TeacherClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherClass");
                });

            modelBuilder.Entity("backend.models.TeacherClass", b =>
                {
                    b.HasOne("backend.models.Teacher", "Teacher")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("backend.models.TestWritten", b =>
                {
                    b.HasOne("backend.models.TeacherClass", "TeacherClass")
                        .WithMany("TestWrittens")
                        .HasForeignKey("TeacherClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherClass");
                });

            modelBuilder.Entity("backend.models.Answer", b =>
                {
                    b.Navigation("AiComments");

                    b.Navigation("TeacherComments");
                });

            modelBuilder.Entity("backend.models.Correction", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("backend.models.Question", b =>
                {
                    b.Navigation("QuestionCriterias");

                    b.Navigation("QuestionTestWrittens");
                });

            modelBuilder.Entity("backend.models.QuestionBank", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("backend.models.QuestionTestWritten", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("backend.models.Student", b =>
                {
                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("backend.models.Teacher", b =>
                {
                    b.Navigation("QuestionBanks");

                    b.Navigation("TeacherClasses");
                });

            modelBuilder.Entity("backend.models.TeacherClass", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TestWrittens");
                });

            modelBuilder.Entity("backend.models.TestWritten", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("QuestionTestWrittens");
                });
#pragma warning restore 612, 618
        }
    }
}
